name: Git Commit/PR → Notion DB (Upsert with multiline + safe ISO date)

on:
  push:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  upsert-notion:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Git 체크아웃
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      # 2️⃣ jq 설치
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # 3️⃣ 커밋/PR 정보 수집 및 임시 파일로 본문 저장
      - name: Collect commit/PR info
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            IDENTIFIER="PR-${{ github.event.pull_request.number }}"
            BRANCH="${{ github.head_ref }}"
            TITLE="${{ github.event.pull_request.title }}"
            AUTHOR="${{ github.event.pull_request.user.login }}"
            DATE_ISO="${{ github.event.pull_request.created_at }}"
            # PR 본문 임시 파일
            echo "${{ github.event.pull_request.body }}" > commit_body.txt
          else
            BRANCH="${GITHUB_REF_NAME#refs/heads/}"
            IDENTIFIER=$(git log -1 --pretty=format:'%H')  # SHA
            TITLE=$(git log -1 --pretty=format:'%s')       # 제목
            AUTHOR=$(git log -1 --pretty=format:'%an')     # 작성자
            DATE_ISO=$(git log -1 --pretty=format:'%cI')   # ISO 8601

            # ✅ 안전 처리: 빈 문자열이면 현재 UTC 시간 적용
            if [ -z "$DATE_ISO" ]; then
              DATE_ISO=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            fi

            # 커밋 본문 임시 파일
            git log -1 --pretty=format:'%b' > commit_body.txt
          fi

      # 4️⃣ Notion DB upsert (PATCH if exists, POST if not)
      - name: Upsert to Notion DB
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          IDENTIFIER: ${{ steps.collect.outputs.IDENTIFIER || '' }}
          TITLE: ${{ steps.collect.outputs.TITLE || '' }}
          AUTHOR: ${{ steps.collect.outputs.AUTHOR || '' }}
          DATE_ISO: ${{ steps.collect.outputs.DATE_ISO || '' }}
          BRANCH: ${{ steps.collect.outputs.BRANCH || '' }}
        run: |
          # JSON 안전 처리: 멀티라인 본문
          BODY_JSON=$(jq -Rs '.' < commit_body.txt)

          # 1️⃣ 기존 페이지 검색
          SEARCH_RESULT=$(curl -s -X POST "https://api.notion.com/v1/databases/$NOTION_DATABASE_ID/query" \
            -H "Authorization: Bearer $NOTION_TOKEN" \
            -H "Notion-Version: 2022-06-28" \
            -H "Content-Type: application/json" \
            -d '{
              "filter": {
                "property": "Identifier",
                "rich_text": { "equals": "'"$IDENTIFIER"'" }
              }
            }')

          PAGE_ID=$(echo "$SEARCH_RESULT" | jq -r '.results[0].id // empty')

          # payload 공통
          JSON_PAYLOAD=$(jq -n \
            --arg title "$TITLE" \
            --arg body "$BODY_JSON" \
            --arg author "$AUTHOR" \
            --arg date_iso "$DATE_ISO" \
            --arg branch "$BRANCH" \
            --arg identifier "$IDENTIFIER" \
            '{
              properties: {
                "Title": { "title": [{ "text": { "content": $title } }] },
                "Body": { "rich_text": [{ "text": { "content": $body } }] },
                "Author": { "rich_text": [{ "text": { "content": $author } }] },
                "Commit Date": { "date": { "start": $date_iso } },
                "Branch": { "select": { "name": $branch } },
                "Identifier": { "rich_text": [{ "text": { "content": $identifier } }] }
              }
            }')

          if [ -n "$PAGE_ID" ]; then
            echo "Existing page found, updating..."
            RESPONSE=$(echo "$JSON_PAYLOAD" | curl -s -X PATCH "https://api.notion.com/v1/pages/$PAGE_ID" \
              -H "Authorization: Bearer $NOTION_TOKEN" \
              -H "Notion-Version: 2022-06-28" \
              -H "Content-Type: application/json" \
              -d @-)
          else
            echo "No existing page, creating new..."
            JSON_CREATE=$(jq -n \
              --arg database_id "$NOTION_DATABASE_ID" \
              --argjson props "$JSON_PAYLOAD" \
              '{parent:{database_id:$database_id}, properties:$props.properties}')
            RESPONSE=$(echo "$JSON_CREATE" | curl -s -X POST "https://api.notion.com/v1/pages" \
              -H "Authorization: Bearer $NOTION_TOKEN" \
              -H "Notion-Version: 2022-06-28" \
              -H "Content-Type: application/json" \
              -d @-)
          fi

          echo "Notion API response: $RESPONSE"
