name: Git Commit → Notion DB

on:
  push:
   # branches:
  pull_request:
    types: [opened, synchronize, closed]# 필요하면 다른 브랜치도 추가 가능

jobs:
  update-notion:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Git 레포 체크아웃
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      # 2️⃣ jq 설치
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # 3️⃣ 최신 커밋 정보 가져오기
      - name: Get last commit info
        id: get_commit
        run: |
          # 현재 브랜치 이름 가져오기
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

          # Git log에서 SHA, 작성자, 제목, 본문, ISO 8601 날짜 가져오기
          git log -1 --pretty=format:'%H%n%an%n%s%n%b%n%cI' > last_commit.txt
          readarray -t arr < last_commit.txt
          COMMIT_SHA="${arr[0]}"
          AUTHOR="${arr[1]}"
          TITLE="${arr[2]}"
          DATE_ISO="${arr[-1]}"

          # 본문 파일에 안전하게 저장
          printf "%s\n" "${arr[@]:3:${#arr[@]}-4}" > commit_body.txt

          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV
          echo "AUTHOR=$AUTHOR" >> $GITHUB_ENV
          echo "TITLE=$TITLE" >> $GITHUB_ENV
          echo "DATE_ISO=$DATE_ISO" >> $GITHUB_ENV

      # 4️⃣ Notion DB에 커밋 기록 추가 (branch 포함)
      - name: Add commit to Notion DB
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          SHA: ${{ env.COMMIT_SHA }}
          AUTHOR: ${{ env.AUTHOR }}
          TITLE: ${{ env.TITLE }}
          DATE_ISO: ${{ env.DATE_ISO }}
          BRANCH: ${{ env.BRANCH_NAME }}
        run: |
          # 본문 안전하게 JSON 문자열로 변환
          BODY_JSON=$(jq -Rs '.' < commit_body.txt)

          # Notion 페이지 JSON
          JSON_PAYLOAD=$(jq -n \
            --arg title "$TITLE" \
            --arg sha "$SHA" \
            --arg author "$AUTHOR" \
            --arg date_iso "$DATE_ISO" \
            --arg branch "$BRANCH" \
            --argjson body "$BODY_JSON" \
            '{
              parent: { database_id: "'$NOTION_DATABASE_ID'" },
              properties: {
                "Title": { "title": [{ "text": { "content": $title } }] },
                "Body": { "rich_text": [{ "text": { "content": $body } }] },
                "Commit SHA": { "rich_text": [{ "text": { "content": $sha } }] },
                "Author": { "rich_text": [{ "text": { "content": $author } }] },
                "Commit Date": { "date": { "start": $date_iso } },
                "Branch": { "select": { "name": $branch } }
              }
            }')

          # Notion API 호출
          response=$(echo "$JSON_PAYLOAD" | curl -s -X POST "https://api.notion.com/v1/pages" \
            -H "Authorization: Bearer $NOTION_TOKEN" \
            -H "Notion-Version: 2022-06-28" \
            -H "Content-Type: application/json" \
            -d @-)

          echo "Notion API response: $response"
