name: Git Commit → Notion DB

# main 브랜치에 push될 때 자동 실행
on:
  push:
    branches:
      - main

jobs:
  update-notion:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Git 레포 체크아웃
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2  # 최소 2개의 커밋 정보 필요

      # 2️⃣ jq 설치 (JSON 파싱용)
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # 3️⃣ 최신 커밋 정보 가져오기
      - name: Get last commit info
        id: get_commit
        run: |
          # Git log에서 각 항목을 줄 단위로 출력
          # %H → SHA, %an → 작성자, %s → 제목, %b → 본문, %cI → 날짜(ISO 8601)
          git log -1 --pretty=format:'%H%n%an%n%s%n%b%n%cI' > last_commit.txt

          # 파일을 배열로 읽어오기
          readarray -t arr < last_commit.txt

          # 환경변수로 저장
          echo "COMMIT_SHA=${arr[0]}" >> $GITHUB_ENV
          echo "AUTHOR=${arr[1]}" >> $GITHUB_ENV
          echo "TITLE=${arr[2]}" >> $GITHUB_ENV

          # 본문(body)은 여러 줄일 수 있으므로 합쳐서 하나의 변수에 저장
          BODY=""
          for ((i=3; i<${#arr[@]}-1; i++)); do
            BODY="$BODY${arr[i]}"$'\n'
          done
          echo "BODY=$BODY" >> $GITHUB_ENV

          # ISO 8601 형식 날짜 (Git log에서 이미 ISO 8601)
          echo "DATE_ISO=${arr[-1]}" >> $GITHUB_ENV

          # 확인용 출력
          echo "Commit date ISO: ${arr[-1]}"
          echo "Commit body: $BODY"

      # 4️⃣ Notion DB에 커밋 기록 추가
      - name: Add commit to Notion DB
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}            # Notion 통합 토큰
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }} # Notion DB ID
          SHA: ${{ env.COMMIT_SHA }}
          AUTHOR: ${{ env.AUTHOR }}
          TITLE: ${{ env.TITLE }}
          BODY: ${{ env.BODY }}
          DATE_ISO: ${{ env.DATE_ISO }}
        run: |
          # 본문을 안전하게 JSON 문자열로 변환 (줄바꿈, 따옴표 포함)
          BODY_JSON=$(echo "$BODY" | jq -Rs '.')

          # Notion 페이지 생성용 JSON 구성
          JSON_PAYLOAD=$(jq -n \
            --arg title "$TITLE" \
            --arg sha "$SHA" \
            --arg author "$AUTHOR" \
            --arg date_iso "$DATE_ISO" \
            --argjson body "$BODY_JSON" \
            '{
              parent: { database_id: "'$NOTION_DATABASE_ID'" },
              properties: {
                "Title": { "title": [{ "text": { "content": $title } }] },
                "Body": { "rich_text": [{ "text": { "content": $body } }] },
                "Commit SHA": { "rich_text": [{ "text": { "content": $sha } }] },
                "Author": { "rich_text": [{ "text": { "content": $author } }] },
                "Commit Date": { "date": { "start": $date_iso } }
              }
            }')

          # Notion API 호출
          response=$(echo "$JSON_PAYLOAD" | curl -s -X POST "https://api.notion.com/v1/pages" \
            -H "Authorization: Bearer $NOTION_TOKEN" \
            -H "Notion-Version: 2022-06-28" \
            -H "Content-Type: application/json" \
            -d @-)

          # API 응답 출력 (디버깅용)
          echo "Notion API response: $response"
