name: Git Commit/PR → Notion DB

on:
  # 모든 브랜치 push 이벤트
  push:

  # PR 이벤트 (생성/병합)
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  update-notion:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Git 레포 체크아웃
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      # 2️⃣ jq 설치
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # 3️⃣ 최신 커밋 정보 가져오기
      - name: Get last commit info
        id: get_commit
        run: |
          # push/PR 구분
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            # PR이면 head ref가 브랜치
            BRANCH_NAME="${{ github.head_ref }}"
          else
            # push이면 현재 브랜치
            BRANCH_NAME="${GITHUB_REF_NAME#refs/heads/}"
          fi
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

          # Git log에서 SHA, 작성자, 제목, 본문, ISO 8601 날짜 가져오기
          git log -1 --pretty=format:'%H%n%an%n%s%n%b%n%cI' > last_commit.txt
          readarray -t arr < last_commit.txt
          COMMIT_SHA="${arr[0]}"
          AUTHOR="${arr[1]}"
          TITLE="${arr[2]}"
          DATE_ISO="${arr[-1]}"

          # 본문(body) 안전하게 파일로 저장
          printf "%s\n" "${arr[@]:3:${#arr[@]}-4}"
