name: Git Commit → Notion DB

on:
  push:
    branches:
      - main

jobs:
  update-notion:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get last commit info
        id: get_commit
        run: |
          # ISO 8601 형식으로 날짜 바로 가져오기
          git log -1 --pretty=format:'%H%n%an%n%s%n%cI' > last_commit.txt
          readarray -t arr < last_commit.txt
          echo "COMMIT_SHA=${arr[0]}" >> $GITHUB_ENV
          echo "AUTHOR=${arr[1]}" >> $GITHUB_ENV
          echo "MESSAGE=${arr[2]}" >> $GITHUB_ENV
          echo "DATE_ISO=${arr[3]}" >> $GITHUB_ENV
          echo "Commit date ISO: ${arr[3]}"

      - name: Add commit to Notion DB
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          SHA: ${{ env.COMMIT_SHA }}
          AUTHOR: ${{ env.AUTHOR }}
          MESSAGE: ${{ env.MESSAGE }}
          DATE_ISO: ${{ env.DATE_ISO }}
        run: |
          response=$(jq -n \
            --arg title "$MESSAGE" \
            --arg sha "$SHA" \
            --arg author "$AUTHOR" \
            --arg date_iso "$DATE_ISO" \
            '{
              parent: { database_id: "'$NOTION_DATABASE_ID'" },
              properties: {
                "Title": { "title": [{ "text": { "content": $title } }] },
                "Commit SHA": { "rich_text": [{ "text": { "content": $sha } }] },
                "Author": { "rich_text": [{ "text": { "content": $author } }] },
                "Commit Date": { "date": { "start": $date_iso } }
              }
            }' | curl -s -X POST "https://api.notion.com/v1/pages" \
                -H "Authorization: Bearer $NOTION_TOKEN" \
                -H "Notion-Version: 2022-06-28" \
                -H "Content-Type: application/json" \
                -d @-)
          echo "Notion API response: $response"
