name: Git Commit → Notion DB

on:
  push:
    branches:
      - main

jobs:
  update-notion:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get last commit info
        id: get_commit
        run: |
          # 커밋 정보: SHA, 작성자, 제목, 본문, ISO 8601 날짜
          git log -1 --pretty=format:'%H%n%an%n%s%n%b%n%cI' > last_commit.txt
          readarray -t arr < last_commit.txt
          echo "COMMIT_SHA=${arr[0]}" >> $GITHUB_ENV
          echo "AUTHOR=${arr[1]}" >> $GITHUB_ENV
          echo "TITLE=${arr[2]}" >> $GITHUB_ENV
          # 본문(body) 줄 합치기
          BODY=""
          for ((i=3; i<${#arr[@]}-1; i++)); do
            BODY="$BODY${arr[i]}"$'\n'
          done
          echo "BODY=$BODY" >> $GITHUB_ENV
          echo "DATE_ISO=${arr[-1]}" >> $GITHUB_ENV
          echo "Commit body: $BODY"

      - name: Add commit to Notion DB
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          SHA: ${{ env.COMMIT_SHA }}
          AUTHOR: ${{ env.AUTHOR }}
          TITLE: ${{ env.TITLE }}
          BODY: ${{ env.BODY }}
          DATE_ISO: ${{ env.DATE_ISO }}
        run: |
          response=$(jq -n \
            --arg title "$TITLE" \
            --arg body "$BODY" \
            --arg sha "$SHA" \
            --arg author "$AUTHOR" \
            --arg date_iso "$DATE_ISO" \
            '{
              parent: { database_id: "'$NOTION_DATABASE_ID'" },
              properties: {
                "Title": { "title": [{ "text": { "content": $title } }] },
                "Body": { "rich_text": [{ "text": { "content": $body } }] },
                "Commit SHA": { "rich_text": [{ "text": { "content": $sha } }] },
                "Author": { "rich_text": [{ "text": { "content": $author } }] },
                "Commit Date": { "date": { "start": $date_iso } }
              }
            }' | curl -s -X POST "https://api.notion.com/v1/pages" \
                -H "Authorization: Bearer $NOTION_TOKEN" \
                -H "Notion-Version: 2022-06-28" \
                -H "Content-Type: application/json" \
                -d @-)
          echo "Notion API response: $response"
