name: Update Notion on Commit

on:
  push:
    branches:
      - main  # main 브랜치에 커밋될 때만 실행
      - jmlee-jira-test # 테스트

jobs:
  update_notion:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update Notion Page
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        COMMIT_URL: ${{ github.event.head_commit.url }}
      run: |
        curl -X PATCH "https://api.notion.com/v1/pages/$NOTION_PAGE_ID" \
        -H "Authorization: Bearer $NOTION_TOKEN" \
        -H "Notion-Version: 2022-06-28" \
        -H "Content-Type: application/json" \
        --data "{
          \"properties\": {
            \"Last Commit\": {
              \"title\": [
                {\"text\": {\"content\": \"${COMMIT_MESSAGE} (${COMMIT_URL})\"}}
              ]
            }
          }
        }"
